---
title: "Exploratory 1"
author: "Maisie Sun"
date: "2022-11-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)
library(patchwork)
library(readxl)
library(rvest)
library(httr)
library(dplyr)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

Get the data

```{r data_import_age}
url = "https://www.health.ny.gov/statistics/vital_statistics/2019/table21.htm"

induced_abortion = 
  read_html(url) %>%
  html_table(header = FALSE) %>%
  first() %>%
  janitor::clean_names()

```

data cleaning

```{r data_cleaning_age}
clean_age = 
  induced_abortion %>%
  select(1:8) %>%
  purrr::set_names(c("county", "total", "age_less_20", "age_20_24", "age_25_29", "age_30_34", "age_35_39", "age_plus_40")) %>%
  slice(6:11) %>%
  rename(borough = county) %>%
  mutate(
    borough = str_replace(borough, "Kings", "Brooklyn"),
    borough = str_replace(borough, "New York City", "New_York_City"),
    borough = str_replace(borough, "New York", "Manhattan"),
    borough = str_replace(borough, "Richmond", "Staten_Island"),
    total = str_replace(total, ",", ""),
    age_less_20 = str_replace(age_less_20, ",", ""),
    age_20_24 = str_replace(age_20_24, ",", ""),
    age_25_29 = str_replace(age_25_29, ",", ""),
    age_30_34 = str_replace(age_30_34, ",", ""),
    age_35_39 = str_replace(age_35_39, ",", ""),
    age_plus_40 = str_replace(age_plus_40, ",", "")
    ) %>%
  mutate_at(c("total", "age_less_20", "age_20_24", "age_25_29", "age_30_34", "age_35_39", "age_plus_40"), as.numeric)
  

```

ggplot: induced abortion vs maternal age

```{r viz_age}
abortion_age_plot = 
  clean_age %>%
  select(-total) %>%
  slice(-1) %>%
  pivot_longer(
    age_less_20:age_plus_40,
    names_to = "age", 
    values_to = "abortion"
  ) %>%
  ggplot(aes(x = age, y = abortion, fill = borough)) + 
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_line(clean_age, )

  scale_y_continuous(
    breaks = c(900, 1000, 111), 
    labels = c("-15ยบ C", "0", "15"))
abortion_age_plot


```

