---
title: "Project Proposal"
author: "Ayako Sekiya (as6445), Daisy Yan (dxy2101), Elaine Chen (yc4017), Kasturi Bhamidipati (kb3246), Maisie Sun (ms6360)"
output: github_document
date: "2022-11-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abortion trends in New York and Mississippi (2017-2020): A Comparative Analysis

### Motivation

In 2019, many conservative states have raced to enact an unprecedented wave on bans on abortions that have severely restricted women’s reproductive rights. These restrictions have culminated with the recent Supreme Court overturning of Roe v. Wade, a landmark supreme court case granting a women’s right to an abortion. Since then access to abortion has been significantly compromised, and even banned, in several states across the country. Those that are likely to be most impacted by this decision are individuals that belong to underserved and marginalized communities. Change in policies could potentially lead to a variation in abortion trends in the country over time.  We can analyze these trends to understand the implications of policy change in the country with respect to reproductive rights.

Our period of interest is from 2017 to 2020. We will be assessing trends in abortion rates leading up to the COVID-19 pandemic, where several abortion clinics closed and people were encouraged to stay at home, underestimating the demand for abortions from 2020 and onwards.

Our areas of interest are New York and Mississippi. Both states have significantly different political alignments and subsequently different policies and trends relating to abortion access and number of abortions.

### Potential Research Questions

* Has abortion rate changed over time (2017 to 2020)?
* What does the distribution of abortion rates among counties within New York and Mississippi look like?
* Do abortion rates differ between New York and Mississippi, accounting for age, race/ethnicity, abortion method, and insurance plan?

### Intended Final Products

Our final project will result in the following:

* Graphs/dashboards depicting the results of our analysis 
* Report explaining our methodology and findings 
* Interactive website with all components of the project
* Screencast going through website

### Anticipated Data Sources

We will be getting data from the Guttmacher Institute: https://data.guttmacher.org/states/table?state=NY+MS&topics=65+66+203+205+152+151+109+110+111+157&dataset=data 

### Planned Analyses / Visualizations / Coding Challenges

*Explanatory Analysis*

We plan to calculate:

* Rate of abortion per 1000 women in New York and Mississippi across 4 years (2017-2020)
* Rate of abortion per 1000 women by age in New York and Mississippi
* Rate of abortion per 1000 women by race/ethnicity in New York and Mississippi
* Rate of abortion per 1000 women by insurance plan in New York and Mississippi

Our outcome of interest is percent change in abortion rate over time. Potential confounders are race/ethnicity, year, methods (induced vs spontaneous), age group, and SES/income/insurance plan.

*Visualizations*

We plan to show:

* Interactive mapping on abortion laws by state throughout time (2017-2020)
* Bar graph during exploratory analysis when comparing New York to Mississippi
* Interactive mapping of abortion rate over time

*Coding challenges*

We may face potential challenges in analyzing the data because they are in group level data.

### Planned Timeline

| Task                                  | Date           |
| ------------------------------------- | -------------- |
| Discuss project ideas                 | Nov 11         |
| Submit project proposal               | Nov 12         |
| Discuss Tasks and allocate work       | Nov 13         |
| Schedule a Review Meeting             | TBD            |
| Work on report, code and website      | Nov 15- Dec 10 |
| Submit report, website and screencast | Dec 10         |
| Submit peer assessment                | Dec 10         |
| Prep for in-class presentations       | Dec 12         |
| In-class presentations                | Dec 15         |

